export const existingMatrix = {
  name: "Popular",
  currencies: [
    {
      name: "Euro",
      code: "EUR",
      country: "Europe",
    },
    {
      name: "US Dollar",
      code: "USD",
      country: "United States",
    },
    {
      name: "Japanese Yen",
      code: "JPY",
      country: "Japan",
    },
    {
      name: "Australian Dollar",
      code: "AUD",
      country: "Australia",
    },
    {
      name: "Swiss Franc",
      code: "CHF",
      country: "Switzerland",
    },
    {
      name: "South African Rand",
      code: "ZAR",
      country: "South Africa",
    },
    {
      name: "New-Zealand Dollar",
      code: "NZD",
      country: "New Zealand",
    },
    {
      name: "British Pound",
      code: "GBP",
      country: "United Kingdom",
    },
    {
      name: "Chinese Renminbi",
      code: "CNY",
      country: "China",
    },
    {
      name: "Hong Kong Dollar",
      code: "HKD",
      country: "Hong Kong",
    },
    {
      name: "Singapore Dollar",
      code: "SGD",
      country: "Singapore",
    },
    {
      name: "Indian Rupee",
      code: "INR",
      country: "India",
    },
  ],
  id: "610120a9e6e845c28991ec2c",
  cells: [
    {
      primary_currency: "AUD",
      secondary_currency: "CAD",
      primary_country: "Australia",
      secondary_country: "Canada",
      change_1d: -0.005,
      price: 0.9158,
      is_opposite: false,
      ws_ticker: "OANDA:AUD_CAD",
    },
    {
      primary_currency: "AUD",
      secondary_currency: "EUR",
      primary_country: "Australia",
      secondary_country: "Europe",
      change_1d: -0.004,
      price: 0.6186,
      is_opposite: true,
      ws_ticker: "OANDA:EUR_AUD",
    },
    {
      primary_currency: "AUD",
      secondary_currency: "CHF",
      primary_country: "Australia",
      secondary_country: "Switzerland",
      change_1d: -0.005,
      price: 0.6649,
      is_opposite: false,
      ws_ticker: "OANDA:AUD_CHF",
    },
    {
      primary_currency: "AUD",
      secondary_currency: "GBP",
      primary_country: "Australia",
      secondary_country: "United Kingdom",
      change_1d: -0.002,
      price: 0.5279,
      is_opposite: true,
      ws_ticker: "OANDA:GBP_AUD",
    },
    {
      primary_currency: "AUD",
      secondary_currency: "NZD",
      primary_country: "Australia",
      secondary_country: "New Zealand",
      change_1d: -0.003,
      price: 1.0525,
      is_opposite: false,
      ws_ticker: "OANDA:AUD_NZD",
    },
    {
      primary_currency: "AUD",
      secondary_currency: "JPY",
      primary_country: "Australia",
      secondary_country: "Japan",
      change_1d: -0.415,
      price: 80.56,
      is_opposite: false,
      ws_ticker: "OANDA:AUD_JPY",
    },

    {
      primary_currency: "CAD",
      secondary_currency: "CHF",
      primary_country: "Canada",
      secondary_country: "Switzerland",
      change_1d: -0.002,
      price: 0.7258,
      is_opposite: false,
      ws_ticker: "OANDA:CAD_CHF",
    },
    {
      primary_currency: "CAD",
      secondary_currency: "GBP",
      primary_country: "Canada",
      secondary_country: "United Kingdom",
      change_1d: 0.001,
      price: 0.5762,
      is_opposite: true,
      ws_ticker: "OANDA:GBP_CAD",
    },
    {
      primary_currency: "CAD",
      secondary_currency: "NZD",
      primary_country: "Canada",
      secondary_country: "New Zealand",
      change_1d: 0.003,
      price: 1.1488,
      is_opposite: true,
      ws_ticker: "OANDA:NZD_CAD",
    },
    {
      primary_currency: "CAD",
      secondary_currency: "AUD",
      primary_country: "Canada",
      secondary_country: "Australia",
      change_1d: 0.005,
      price: 1.0913,
      is_opposite: true,
      ws_ticker: "OANDA:AUD_CAD",
    },
    {
      primary_currency: "CAD",
      secondary_currency: "EUR",
      primary_country: "Canada",
      secondary_country: "Europe",
      change_1d: -0.001,
      price: 0.6753,
      is_opposite: true,
      ws_ticker: "OANDA:EUR_CAD",
    },
    {
      primary_currency: "CAD",
      secondary_currency: "JPY",
      primary_country: "Canada",
      secondary_country: "Japan",
      change_1d: -0.025,
      price: 87.94,
      is_opposite: false,
      ws_ticker: "OANDA:CAD_JPY",
    },

    {
      primary_currency: "CHF",
      secondary_currency: "EUR",
      primary_country: "Switzerland",
      secondary_country: "Europe",
      change_1d: 0.002,
      price: 0.9299,
      is_opposite: true,
      ws_ticker: "OANDA:EUR_CHF",
    },
    {
      primary_currency: "CHF",
      secondary_currency: "JPY",
      primary_country: "Switzerland",
      secondary_country: "Japan",
      change_1d: 0.3,
      price: 121.11,
      is_opposite: false,
      ws_ticker: "OANDA:CHF_JPY",
    },
    {
      primary_currency: "CHF",
      secondary_currency: "AUD",
      primary_country: "Switzerland",
      secondary_country: "Australia",
      change_1d: 0.011,
      price: 1.5029,
      is_opposite: true,
      ws_ticker: "OANDA:AUD_CHF",
    },
    {
      primary_currency: "CHF",
      secondary_currency: "NZD",
      primary_country: "Switzerland",
      secondary_country: "New Zealand",
      change_1d: 0.008,
      price: 1.5821,
      is_opposite: true,
      ws_ticker: "OANDA:NZD_CHF",
    },
    {
      primary_currency: "CHF",
      secondary_currency: "CAD",
      primary_country: "Switzerland",
      secondary_country: "Canada",
      change_1d: 0.003,
      price: 1.3767,
      is_opposite: true,
      ws_ticker: "OANDA:CAD_CHF",
    },
    {
      primary_currency: "CHF",
      secondary_currency: "GBP",
      primary_country: "Switzerland",
      secondary_country: "United Kingdom",
      change_1d: 0.003,
      price: 0.7936,
      is_opposite: true,
      ws_ticker: "OANDA:GBP_CHF",
    },

    {
      primary_currency: "EUR",
      secondary_currency: "CAD",
      primary_country: "Europe",
      secondary_country: "Canada",
      change_1d: 0.001,
      price: 1.4802,
      is_opposite: false,
      ws_ticker: "OANDA:EUR_CAD",
    },
    {
      primary_currency: "EUR",
      secondary_currency: "CHF",
      primary_country: "Europe",
      secondary_country: "Switzerland",
      change_1d: -0.002,
      price: 1.0747,
      is_opposite: false,
      ws_ticker: "OANDA:EUR_CHF",
    },
    {
      primary_currency: "EUR",
      secondary_currency: "GBP",
      primary_country: "Europe",
      secondary_country: "United Kingdom",
      change_1d: 0.002,
      price: 0.8532,
      is_opposite: false,
      ws_ticker: "OANDA:EUR_GBP",
    },
    {
      primary_currency: "EUR",
      secondary_currency: "AUD",
      primary_country: "Europe",
      secondary_country: "Australia",
      change_1d: 0.008,
      price: 1.6158,
      is_opposite: false,
      ws_ticker: "OANDA:EUR_AUD",
    },
    {
      primary_currency: "EUR",
      secondary_currency: "JPY",
      primary_country: "Europe",
      secondary_country: "Japan",
      change_1d: 0.05,
      price: 130.21,
      is_opposite: false,
      ws_ticker: "OANDA:EUR_JPY",
    },
    {
      primary_currency: "EUR",
      secondary_currency: "NZD",
      primary_country: "Europe",
      secondary_country: "New Zealand",
      change_1d: 0.005,
      price: 1.7011,
      is_opposite: false,
      ws_ticker: "OANDA:EUR_NZD",
    },

    {
      primary_currency: "GBP",
      secondary_currency: "AUD",
      primary_country: "United Kingdom",
      secondary_country: "Australia",
      change_1d: 0.005,
      price: 1.8931,
      is_opposite: false,
      ws_ticker: "OANDA:GBP_AUD",
    },
    {
      primary_currency: "GBP",
      secondary_currency: "CAD",
      primary_country: "United Kingdom",
      secondary_country: "Canada",
      change_1d: -0.004,
      price: 1.7342,
      is_opposite: false,
      ws_ticker: "OANDA:GBP_CAD",
    },
    {
      primary_currency: "GBP",
      secondary_currency: "EUR",
      primary_country: "United Kingdom",
      secondary_country: "Europe",
      change_1d: -0.003,
      price: 1.1714,
      is_opposite: true,
      ws_ticker: "OANDA:EUR_GBP",
    },
    {
      primary_currency: "GBP",
      secondary_currency: "JPY",
      primary_country: "United Kingdom",
      secondary_country: "Japan",
      change_1d: -0.3,
      price: 152.56,
      is_opposite: false,
      ws_ticker: "OANDA:GBP_JPY",
    },
    {
      primary_currency: "GBP",
      secondary_currency: "CHF",
      primary_country: "United Kingdom",
      secondary_country: "Switzerland",
      change_1d: -0.006,
      price: 1.2591,
      is_opposite: false,
      ws_ticker: "OANDA:GBP_CHF",
    },
    {
      primary_currency: "GBP",
      secondary_currency: "NZD",
      primary_country: "United Kingdom",
      secondary_country: "New Zealand",
      change_1d: 0.001,
      price: 1.993,
      is_opposite: false,
      ws_ticker: "OANDA:GBP_NZD",
    },
    {
      primary_currency: "JPY",
      secondary_currency: "EUR",
      primary_country: "Japan",
      secondary_country: "Europe",
      change_1d: 0,
      price: 0.0077,
      is_opposite: true,
      ws_ticker: "OANDA:EUR_JPY",
    },
    {
      primary_currency: "JPY",
      secondary_currency: "CAD",
      primary_country: "Japan",
      secondary_country: "Canada",
      change_1d: 0,
      price: 0.0114,
      is_opposite: true,
      ws_ticker: "OANDA:CAD_JPY",
    },
    {
      primary_currency: "JPY",
      secondary_currency: "CHF",
      primary_country: "Japan",
      secondary_country: "Switzerland",
      change_1d: 0,
      price: 0.0083,
      is_opposite: true,
      ws_ticker: "OANDA:CHF_JPY",
    },
    {
      primary_currency: "JPY",
      secondary_currency: "GBP",
      primary_country: "Japan",
      secondary_country: "United Kingdom",
      change_1d: 0,
      price: 0.0066,
      is_opposite: true,
      ws_ticker: "OANDA:GBP_JPY",
    },
    {
      primary_currency: "JPY",
      secondary_currency: "AUD",
      primary_country: "Japan",
      secondary_country: "Australia",
      change_1d: 0,
      price: 0.0124,
      is_opposite: true,
      ws_ticker: "OANDA:AUD_JPY",
    },
    {
      primary_currency: "JPY",
      secondary_currency: "NZD",
      primary_country: "Japan",
      secondary_country: "New Zealand",
      change_1d: 0,
      price: 0.0131,
      is_opposite: true,
      ws_ticker: "OANDA:NZD_JPY",
    },

    {
      primary_currency: "NZD",
      secondary_currency: "AUD",
      primary_country: "New Zealand",
      secondary_country: "Australia",
      change_1d: 0.002,
      price: 0.9494,
      is_opposite: true,
      ws_ticker: "OANDA:AUD_NZD",
    },
    {
      primary_currency: "NZD",
      secondary_currency: "CAD",
      primary_country: "New Zealand",
      secondary_country: "Canada",
      change_1d: -0.003,
      price: 0.8697,
      is_opposite: false,
      ws_ticker: "OANDA:NZD_CAD",
    },
    {
      primary_currency: "NZD",
      secondary_currency: "EUR",
      primary_country: "New Zealand",
      secondary_country: "Europe",
      change_1d: -0.002,
      price: 0.5874,
      is_opposite: true,
      ws_ticker: "OANDA:EUR_NZD",
    },
    {
      primary_currency: "NZD",
      secondary_currency: "GBP",
      primary_country: "New Zealand",
      secondary_country: "United Kingdom",
      change_1d: -0.001,
      price: 0.5013,
      is_opposite: true,
      ws_ticker: "OANDA:GBP_NZD",
    },
    {
      primary_currency: "NZD",
      secondary_currency: "JPY",
      primary_country: "New Zealand",
      secondary_country: "Japan",
      change_1d: -0.25,
      price: 76.5,
      is_opposite: false,
      ws_ticker: "OANDA:NZD_JPY",
    },
    {
      primary_currency: "NZD",
      secondary_currency: "CHF",
      primary_country: "New Zealand",
      secondary_country: "Switzerland",
      change_1d: -0.004,
      price: 0.6314,
      is_opposite: false,
      ws_ticker: "OANDA:NZD_CHF",
    },
  ],
};
